### ISSUE TITLE
Stake stickers show on back side of jokers when encounting Amber Acorn

### ISSUE THREAD

**Issue by Dilant** [SirMaiquis/Balatro-Stickers-Always-Shown#1]
I forgot to take a screenshot, but I think the title clearly shows the problem.

The player can then identify the jokers by these stickers, is this intended?

**Comment by SirMaiquis** [comment]
It's quite odd that you're encountering this issue, as I had previously observed and addressed this specific behavior during the early development stages of the mod. The functionality was explicitly designed to display the stickers only on the front face of the jokers. After implementing the fix, my subsequent tests showed that the issue had been resolved.

I’ll run more tests to verify this isn’t happening due to recent updates or specific game scenarios like Amber Acorn.

**Comment by SirMaiquis** [comment]
Thanks for letting me know, the issue is resolved now ! 🃏

**Comment by Dilant** [comment]
The fix is working for me, thank you!
